'use client'
import '../styles/styles.css'

import ErrorBoundary from '@/app/error-boundary/components/error-boundary'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <aside>
          <ul className="sidebar" style={{ listStyle: 'none', padding: 0 }}>
            <li>
              Controlled vs Uncontolled
              <ul>
                <a href={'/controlled-uncontrolled/controlled'}>
                  <li>Controlled</li>
                </a>
                <a href={'/controlled-uncontrolled/uncontrolled'}>
                  <li>Uncontrolled</li>
                </a>
              </ul>
            </li>
            <li>
              createElement vs cloneElement
              <ul>
                <a href={'/createElement-cloneElement/createElement'}>
                  <li>createElement</li>
                </a>
                <a href={'/createElement-cloneElement/cloneElement'}>
                  <li>cloneElement</li>
                </a>
              </ul>
            </li>
            <li>
              HOC
              <ul>
                <a href={'/HOC/basic'}>
                  <li>Basic</li>
                </a>
                <a href={'/HOC/advanced'}>
                  <li>Advanced</li>
                </a>
              </ul>
            </li>
            <li>
              Context
              <ul>
                <a href={'/context/my-solution'}>
                  <li>My Solution</li>
                </a>
                <a href={'/context/docs-solution'}>
                  <li>Docs Solution</li>
                </a>
              </ul>
            </li>
            <li>
              React Portal
              <ul>
                <a href={'/react-portal'}>
                  <li>React Portal</li>
                </a>
              </ul>
            </li>
            <li>
              Error Boundary
              <ul>
                <a href={'/error-boundary'}>
                  <li>Error Boundary</li>
                </a>
              </ul>
            </li>
            <li>
              Compound Components
              <ul>
                <a href={'/compound-components'}>
                  <li>Compound Components</li>
                </a>
              </ul>
            </li>
          </ul>
        </aside>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <ErrorBoundary fallback={<h1>최상위에서 Error 발생</h1>}>
            {children}
          </ErrorBoundary>
        </div>
      </body>
    </html>
  )
}
