import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={inter.className}>  <aside>
        <ul style={{listStyle: 'none', padding: 0}}>
          <li>Controlled vs Uncontolled
            <ul>
              <a href={'/controlled-uncontrolled/controlled'}><li >Controlled</li></a>
              <a href={'/controlled-uncontrolled/uncontrolled'}><li>Uncontrolled</li></a>
            </ul>
          </li>
        </ul>
      </aside>
      <div style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>{children}</div>
      </body>
    </html>
  )
}
